title: Sobre mi
description: Mi sitio personal donde podrás saber sobre mi y mi contacto
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme